databaseChangeLog:
  # ################
  # Alert - Add column
  # ################
  - changeSet:
      preConditions:
        - onFail: MARK_RAN
        - not:
            columnExists:
              tableName: ${gravitee_prefix}alert_triggers
              columnName: environment_id
      id: 3.18.0_alert
      author: GraviteeSource Team
      validCheckSum: ANY
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}alert_triggers
            columns:
              - column:
                  name: environment_id
                  type: nvarchar(64)
                  constraints:
                    nullable: true

  # ################
  # Commands - Add column
  # ################
  - changeSet:
      preConditions:
        - onFail: MARK_RAN
        - not:
            columnExists:
              tableName: ${gravitee_prefix}commands
              columnName: organization_id
      id: 3.18.0_commands
      author: GraviteeSource Team
      validCheckSum: ANY
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}commands
            columns:
              - column:
                  name: organization_id
                  type: nvarchar(64)
                  value: 'DEFAULT'
                  constraints:
                    nullable: false
              - dropNotNullConstraint:
                  columnDataType: nvarchar(64)
                  columnName: environment_id
                  tableName: ${gravitee_prefix}commands


  # ################
  # Audits - Add column
  # ################
  - changeSet:
      preConditions:
        - onFail: MARK_RAN
        - not:
            columnExists:
              tableName: ${gravitee_prefix}audits
              columnName: environment_id
      id: 3.18.0_audits_add_column
      author: GraviteeSource Team
      validCheckSum: ANY
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}audits
            columns:
              - column:
                  name: organization_id
                  type: nvarchar(64)
                  value: 'DEFAULT'
                  constraints:
                    nullable: true
              - column:
                  name: environment_id
                  type: nvarchar(64)
                  value: 'DEFAULT'
                  constraints:
                    nullable: true
        - createIndex:
            tableName: ${gravitee_prefix}audits
            indexName: idx_${gravitee_prefix}organization_environment
            columns:
              - column:
                  name: organization_id
                  type: nvarchar(64)
              - column:
                  name: environment_id
                  type: nvarchar(64)
  # ################
  # Audits - Update organization_id & environment_id if needed
  # ################
  - changeSet:
      preConditions:
        - onFail: MARK_RAN
        - not:
            sqlCheck:
              expectedResult: 1
              sql: select count(*) from ${gravitee_prefix}environments
      id: 3.18.0
      author: GraviteeSource Team
      validCheckSum: ANY
      changes:
        # mssql
        - sql:
            dbms: mssql
            sql: UPDATE ${gravitee_prefix}audits SET organization_id = reference_id WHERE reference_type = 'ORGANIZATION';
        - sql:
            dbms: mssql
            sql: |
              UPDATE a
              SET organization_id = coalesce(e.organization_id, 'DEFAULT'), environment_id = coalesce(e.id, 'DEFAULT')
              FROM ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}environments e on e.id = a.reference_id
              WHERE a.reference_type = 'ENVIRONMENT';
        - sql:
            dbms: mssql
            sql: |
              UPDATE a
              SET organization_id = coalesce(e.organization_id, 'DEFAULT'), environment_id = coalesce(e.id, 'DEFAULT')
              FROM ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}apis apis on a.reference_id = apis.id
              LEFT JOIN ${gravitee_prefix}environments e on e.id = apis.environment_id
              WHERE a.reference_type = 'API';
        - sql:
            dbms: mssql
            sql: |
              UPDATE a
              SET organization_id = coalesce(e.organization_id, 'DEFAULT'), environment_id = coalesce(e.id, 'DEFAULT')
              FROM ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}applications app on a.reference_id = app.id
              LEFT JOIN ${gravitee_prefix}environments e on e.id = app.environment_id
              WHERE a.reference_type = 'APPLICATION';
        # postgresql
        - sql:
            dbms: postgresql
            sql: UPDATE ${gravitee_prefix}audits SET organization_id = reference_id WHERE reference_type = 'ORGANIZATION';
        - sql:
            dbms: postgresql
            sql: |
              UPDATE ${gravitee_prefix}audits ua
              SET organization_id = coalesce(e.organization_id, 'DEFAULT'), environment_id = coalesce(e.id, 'DEFAULT')
              FROM ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}environments e on e.id = a.reference_id
              WHERE ua.id = a.id AND a.reference_type = 'ENVIRONMENT';
        - sql:
            dbms: postgresql
            sql: |
              UPDATE ${gravitee_prefix}audits ua
              SET organization_id = coalesce(e.organization_id, 'DEFAULT'), environment_id = coalesce(e.id, 'DEFAULT')
              FROM ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}apis apis on a.reference_id = apis.id
              LEFT JOIN ${gravitee_prefix}environments e on e.id = apis.environment_id
              WHERE ua.id = a.id AND a.reference_type = 'API';
        - sql:
            dbms: postgresql
            sql: |
              UPDATE ${gravitee_prefix}audits ua
              SET organization_id = coalesce(e.organization_id, 'DEFAULT'), environment_id = coalesce(e.id, 'DEFAULT')
              FROM ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}applications app on a.reference_id = app.id
              LEFT JOIN ${gravitee_prefix}environments e on e.id = app.environment_id
              WHERE ua.id = a.id AND a.reference_type = 'APPLICATION';
        # mariadb, mysql
        - sql:
            dbms: mariadb, mysql
            sql: UPDATE ${gravitee_prefix}audits SET organization_id = reference_id WHERE reference_type = 'ORGANIZATION';
        - sql:
            dbms: mariadb, mysql
            sql: |
              UPDATE ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}environments e on e.id = a.reference_id
              SET a.organization_id = coalesce(e.organization_id, 'DEFAULT'), environment_id = coalesce(e.id, 'DEFAULT')
              WHERE a.reference_type = 'ENVIRONMENT';
        - sql:
            dbms: mariadb, mysql
            sql: |
              UPDATE ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}apis apis on a.reference_id = apis.id
              LEFT JOIN ${gravitee_prefix}environments e on e.id = apis.environment_id
              SET a.organization_id = coalesce(e.organization_id, 'DEFAULT'), a.environment_id = coalesce(e.id, 'DEFAULT')
              WHERE a.reference_type = 'API';
        - sql:
            dbms: mariadb, mysql
            sql: |
              UPDATE ${gravitee_prefix}audits a
              LEFT JOIN ${gravitee_prefix}applications app on a.reference_id = app.id
              LEFT JOIN ${gravitee_prefix}environments e on e.id = app.environment_id
              SET a.organization_id = coalesce(e.organization_id, 'DEFAULT'), a.environment_id = coalesce(e.id, 'DEFAULT')
              WHERE a.reference_type = 'APPLICATION';

  # ################
  # ClientRegistrationProvider - Add new column
  # ################
  - changeSet:
      preConditions:
        - onFail: MARK_RAN
        - not:
            columnExists:
              tableName: ${gravitee_prefix}client_registration_providers
              columnName: environment_id
      id: 3.18.0_client_registration_providers
      author: GraviteeSource Team
      validCheckSum: ANY
      changes:
        - addColumn:
              tableName: ${gravitee_prefix}client_registration_providers
              columns:
                  - column:
                        name: environment_id
                        type: nvarchar(64)
                        value: 'DEFAULT'
                        constraints:
                            nullable: true
        - createIndex:
              tableName: ${gravitee_prefix}client_registration_providers
              indexName: idx_${gravitee_prefix}environment
              columns:
                  - column:
                        name: environment_id
                        type: nvarchar(64)